### ISSUE TITLE
Occasional loom_infer crash 

### ISSUE THREAD

**Issue by fritzo** [priorknowledge/loom#29]
<pre>
======================================================================
ERROR: loom.test.test_happy_path.test_all('mixed-100-100-0.05',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/sf/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/vagrant/sf/loom/loom/test/util.py", line 62, in test_one
    fun(name=dataset, **files)
  File "/home/vagrant/sf/loom/loom/test/test_happy_path.py", line 104, in test_all
    debug=True)
  File "/home/vagrant/sf/loom/loom/runner.py", line 159, in infer
    check_call(command, debug, profile)
  File "/home/vagrant/sf/loom/loom/runner.py", line 83, in check_call
    subprocess.check_call(command, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['/home/vagrant/sf/loom/build/debug/src/loom_infer', '/tmp/user/1000/tmpjnoAjx/config.pb.gz', '/tmp/user/1000/tmpjnoAjx/shuffled.pbs.gz', '/tmp/user/1000/tmpjnoAjx/init.pb.gz', '--none', '--none', '--none', '/tmp/user/1000/tmpjnoAjx/model.pb.gz', '/tmp/user/1000/tmpjnoAjx/groups', '/tmp/user/1000/tmpjnoAjx/assign.pbs.gz', '--none', '/tmp/user/1000/tmpjnoAjx/log.pbs.gz']' returned non-zero exit status -6
--------------------  begin captured stdout  ---------------------
cd /tmp/user/1000/tmpjnoAjx
making encoding
Running _make_encoder_builders_file in 4 threads
importing rows
cd /tmp/user/1000/tmpQek9Gw
Running _import_rows_file in 4 threads
cd /tmp/user/1000/tmpjnoAjx
generating init
shuffling rows
creating config
inferring
/home/vagrant/sf/loom/build/debug/src/loom_infer \
  /tmp/user/1000/tmpjnoAjx/config.pb.gz \
  /tmp/user/1000/tmpjnoAjx/shuffled.pbs.gz \
  /tmp/user/1000/tmpjnoAjx/init.pb.gz \
  --none \
  --none \
  --none \
  /tmp/user/1000/tmpjnoAjx/model.pb.gz \
  /tmp/user/1000/tmpjnoAjx/groups \
  /tmp/user/1000/tmpjnoAjx/assign.pbs.gz \
  --none \
  /tmp/user/1000/tmpjnoAjx/log.pbs.gz
cd /home/vagrant/sf/loom

ERROR duplicate key: 0
    /home/vagrant/.virtualenvs/sf/include/distributions/sparse.hpp : 70
    void distributions::Sparse_<Key, Value>::add(const Key&, const Value&) [with Key = unsigned int, Value = float]
</pre>

**Comment by fritzo** [comment]
Loom commit: 28af8bd74e1ca893cbcb0e6f70ea6e1378a414a4
