### ISSUE TITLE
Mutual information tests fail more than 10% of the time (flapper)

### ISSUE THREAD

**Issue by fritzo** [priorknowledge/loom#39]
# 
## FAIL: loom.test.test_query_math.test_mi_entropy_relations('dpd-10-10-0.5',)

Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/sf/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(_self.arg)
  File "/home/ubuntu/sf/loom/loom/test/util.py", line 54, in test_one
    fun(name=dataset, *_files)
  File "/home/ubuntu/sf/loom/loom/test/test_query_math.py", line 118, in test_mi_entropy_relations
    assert_less_equal(abs(actual - expected), Z_SCORE \* error)
AssertionError: 0.20141252150138211 not less than or equal to 0.18569849313900016

**Comment by jglidden** [comment]
This should be fixed by: https://github.com/priorknowledge/loom/pull/44
