### ISSUE TITLE
Type error in test_samples_match_scores

### ISSUE THREAD

**Issue by fritzo** [priorknowledge/loom#56]
<pre>
======================================================================
ERROR: loom.test.test_query_math.test_samples_match_scores('dpd-100-10-0.05',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fritz/.virtualenvs/sf/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/fritz/sf/loom/loom/test/util.py", line 60, in test_one
    fun(**kwargs)
  File "/home/fritz/sf/loom/loom/test/test_query_math.py", line 124, in test_samples_match_scores
    _check_marginal_samples_match_scores(server, row, 0)
  File "/home/fritz/sf/loom/loom/test/test_query_math.py", line 103, in _check_marginal_samples_match_scores
    assert_almost_equal(probs_dict[sample], 1., places=SCORE_TOLERANCE)
  File "/usr/lib/python2.7/unittest/case.py", line 552, in assertAlmostEqual
    if round(abs(second-first), places) == 0:
TypeError: 'float' object cannot be interpreted as an index
</pre>

**Comment by fritzo** [comment]
The problem line is `places=SCORE_TOLERANCE`

**Comment by fritzo** [comment]
fixed in f32812b
