### ISSUE TITLE
multiple calls to score_derivate cause error

### ISSUE THREAD

**Issue by jglidden** [priorknowledge/loom#84]
On branch: https://github.com/priorknowledge/loom/tree/similar

<pre>
>> nosetests -sx test_query:test_score_derivative_can_run
....ERROR stale global id: 8
        /home/ubuntu/.virtualenvs/sf/include/distributions/mixture.hpp : 508
        distributions::MixtureIdTracker::Id distributions::MixtureIdTracker::global_to_packed(distributions::MixtureIdTracker::Id) const
E
======================================================================
ERROR: test_query.test_score_derivative_can_run('nich-10-10-0.5',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/sf/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/sf/loom/loom/test/util.py", line 61, in test_one
    fun(**kwargs)
  File "/home/ubuntu/sf/loom/loom/test/test_query.py", line 187, in test_score_derivative_can_run
    diffs = server.score_derivative(row, row_limit=1)
  File "/home/ubuntu/sf/loom/loom/query.py", line 270, in score_derivative
    response = self.protobuf_server.receive()
  File "/home/ubuntu/sf/loom/loom/query.py", line 297, in receive
    response_string = protobuf_stream_read(self.proc.stdout)
  File "/home/ubuntu/sf/distributions/distributions/io/stream.py", line 140, in protobuf_stream_read
    raise StopIteration
StopIteration

----------------------------------------------------------------------
Ran 5 tests in 0.365s

FAILED (errors=1)
</pre>

Note that line 187 in test_preql.py where the error occurs is the second call to `similar` on a running query server.

**Comment by fritzo** [comment]
Fixed in https://github.com/priorknowledge/loom/commit/b49eb28cad91fc6a8cd1845639dfbe7da945f0a3
